language: python
python:
- 3.4
branches:
  only:
  - master
git:
  depth: 5
install:
- pip install -r requirements.txt
script:
- invoke travis
env:
  global:
  - secure: W/CBR2SayGf5Xl5JCICdsmLRCVNYmuq4flQiwFDAX3vu4hffh82OqacWb1WKXuFuISmup8Aa+qQqfLmGoAVbb1+Gs/5PFJU3P1mvVtzcF/lXh5wHrcK8XcgxLrXPU8Ia46044AdAoolvpjHRQIPHlxLUQTF8qPwu5OoMwf0vDGEkz1qKvUQmXlF3BSwuU9sxvsHXK/l6GeJmNuGQV9OGgn4WHIOB/kk/V0vDKwGcMYLil827tF2nUpkB4uEZ2n2uRffUZ23yjAQCEtOAgqF6fn4Fzvn/jKocGr7+VOD9pCYRFqH9vtko2aVTCBkrL0hbjt6mwbmphq1cKKN6xm3StkQD7ClkvuHi6VdGA3RmaPHNwCb7qwY6ze7ZsGWllqNFur4TE0k5fIqhMiVaYALO7Jit6GBAzajJiwxmU+cGWURz32Ub85I0WmtqwduZpDqP985swtfJP5qMv192NUJVrzV8b0OPzC72ZNu3DAYKZ2R9fJlyA2SK6ChVk3CeOs0cHwiyRQU09J/hwhliwbzYNbHT30QCsUbM9irWWDtqCRKykTOT9yeu5k4RPQ4XD1Ep7FK3Nv/WRpiI3VmYQxOinwrV9gVP1kkeNIQTRvhOU4ia6McZi9d+sLCRcgQDxysAraIkp3cHZlQQ9mo3qRT5h0Pk6sjR6pBGA29YwNmE+/I=
  - secure: rd1YAIJs5DEgnViLST6DOBEyQ94WV+mRDJSCVpiaaL9fKAPVh1KfQo1gtNoanI5P5u2k5qs8nSXrge90q8TJ5iThUyp/zkJVFVB06hq745c/U3G+cUKt0m9/Aw2TgRTfC4Xf2avSG1Tp5ELFk2O0nz/Xy0vbJgVEDmnGn7QEdGHrn+9FFDWQf7O1NrKyouX0godLF0e3k8+8IbjjmnQYLC2tKo+iQ4atD5LobaQdcZ+07I7jdHFDhthUF5MLJhGUVJkURDNivhG1RocUGLvb9yB6Mb+ExhAn/KctzW6kCAQ0t47ijbI3LsHGU1DXGDWe7tVxpH4SJijnI6bGPBr9paZs2IwMlB7naGdWzbOwtyujrXj72s2lelkmJtAEkMdPvR1bYu2EcCPjuptTsUy5NYDJvx7Wnr73lexHTmvge+U0RYvAOIuMhAO8qhXXDJTNhESqwGtwLI7J989eJKxzxnOpcXGXs47alJsJiN4wFFSh0rCym5JOeSKL5XB8MjJ7jKS6eqng48Cz/anWU/u4bBuY56McLm8lq7zByay33oFkcmMiWYPsM0tgl7Gz6SgurV7gRkJQ74ArU0/nYuIAKTKw0V2ntReys711mQWAEPR1kaVgnLl7Bx1Rm5LJ+2uTPrk4CH3PEn6aoNGI9RpH5hqW87K8IOMSDsTcUhq0E9w=
