language: python
python:
  - 3.4
branches:
  only:
    - master
git:
  depth: 5

env:
  global:
    - secure: "BcoovGN7zxC3t0neqBHjalM7fhs1SuqCXqvzel74RLOa32ONsYgaN1amrrm+hGtyPrfObRuf8rTYPbCSZCplp/9LO8C6zaGgpMoJr0mWJ4zqHQI23ztzgbonfP3P5vMZU/F0zVHKfMqPsnPqmcuIIMFwjWSNl6qflUVl/q4YO6/D73qUKpbX2q/W6ymljzdtp6WdvVnh8c3DTNYBxGvdP/ZU3oSN6wJPeXYJXxvNUWLYOe1gyOqkAiywIwO0qCG2Fr/rJe/Wjia1fLNHaDmkOQO2i8FIrELujNWzNDrpkenM7YIXRl4jqRMwRBvETFM0Ij0uxD7U+qFWgQ97xojoQeZwu3EXviCaEo2J7nzdQ4pM6iwigVNxqnCf8nPHNOtDPnZbgPcD2X8yzxK92llBulhZKjjviug4zTguSyW2k5iGEPs0snT4C2Yw4KNI5O6A6dACWXY27fQe2edl5qZpzU7AB4+gjd0sVaaYEV+eUrLxCrkSD9cbmLuzwsGEWAGBLAICa6ZRdG+Do/6/otNE5N32VDa0skbaLcD7qKr7Ccr4Kxrqk75Wv7lOwWiLQndv95LpSUujAPiKiN342YR8gBvWzBBkfIs8xbjR0/zO/GO3IgBNGGbO0A+/0No4Dr1FYu4Bna3CTc52ZTGud0WgABdE4gdkohf3ti4GUuG3g34="
install:
  - pip install -r requirements.txt
script:
  - invoke travis
