language: python
python:
  - 3.4
branches:
  only:
    - master
git:
  depth: 5

env:
  global:
    - secure: "BQcoRAjAzBav2poBjkiDIB65t0BdzxVHDwbb4b/2njhdaq8XASMuqB9SnaZKjUHqOjsx+D3B5oXmWoafRWMFH7gWAfBLBEm9ivKCTGZMVHUwKs0ywBSQQV3nI7isG4uEcAvEH7g2yHfWitJmb+9JEbhHA3ugVBSLLfpgPDun8ZCGwVRSSbUDoNuHG4NXKytX29n6ZmgJUTccbNiWBKRd2wUcbCzvV+9iGCfQNA/Gi6PUSvhv+6wA027bKt8+PSXmqKjLZKnRukvEPVY5iCOlE+XPpCkSAC8hYqfiArfhscvZEbwdXZHVOv5iiYxncG4VS0qgB9YS8lmnDG2yGM9ANEGVVUf7y2X8qSnfDtdOm4mqJUYnQ5VULf6REZ0JLoFiT4kA//YtBJha/aa8JoJvi1v5limPyOpA7hCI79WzzCNUgF3HwiDWJqO1aYXW8ORfyUBxqfL0UzKxO6U19EQ3CTZA/DVDMdrQW18iCruSvxFrgFbMy3WlK9VPVsaJFfieFegoxOyPyi+HuxEIa+h3iTLYI+B/7yBPrxBNafJaU3Abd/7J0/XmrTa8cb0Z9OThNW/HL+RbLotfcLG5RwD4wHxrg1cpmEKlHazkPUsSoP0pMMPK46n3PU8d/fpz2T1I5zMkKP/6LjTNjX3eX7Wo1bzk2KTAWaBO0lITdWT3raw="
install:
  - pip install -r requirements.txt
script:
  - invoke travis
